### ISSUE TITLE
I met a problem when I built a gradle project

### ISSUE THREAD

**Issue by lokisama** [ArcBees/gwtquery-droppable-plugin#13]
Excuse me , I always cant build a gradle project successfully. At first gwtVersion is 2.6.1, then I tried to set gwtVersion to 2.7.0, it still failed.

gwt-user:2.7.0
gwt-dev:2.7.0
gwtquery:1.4.2
draggable:2.0-SNAPSHOT
droppable:2.0-SNAPSHOT

Do u have time to have a look ? Would u like to have a look at my build.gradle?

ERROR:

Compiling module com.doggie.run.App
Tracing compile failure path for type 'gwtquery.plugins.droppable.client.gwt.DragAndDropCellTree'
[ERROR] Errors in 'gwtquery/plugins/droppable/client/gwt/DragAndDropCellTree.java'
[ERROR] Line 112: The constructor DragAndDropCellTreeNodeView(DragAndDropCellTree, CellTreeNodeView<?>, TreeViewModel.NodeInfo, Element, T, CellTree.CellTreeMessages) refers to the missing type CellTreeNodeView
[ERROR] Line 111: The method createTreeNodeView(T, CellTree.CellTreeMessages) of type DragAndDropCellTree must override or implement a supertype method
[ERROR] Line 42: The type com.google.gwt.user.cellview.client.CellTreeNodeView is not visible
[ERROR] Line 111: CellTreeNodeView cannot be resolved to a type
Tracing compile failure path for type 'gwtquery.plugins.droppable.client.gwt.DragAndDropCellBrowser'
[ERROR] Errors in 'gwtquery/plugins/droppable/client/gwt/DragAndDropCellBrowser.java'
[ERROR] Line 183: The type CellBrowser.BrowserCellList is not visible
[ERROR] Line 306: The method getLoadingIndicator() is undefined for the type DragAndDropCellBrowser
[ERROR] Line 158: The type CellBrowser.BrowserCellList is not visible
[ERROR] Line 302: The type BrowserCellList is not visible

**Comment by lokisama** [comment]
HI, I have solved this problem. this droppable package should be put before gwt defult package.Thank you.

**Comment by olafleur** [comment]
Super. Closing, then. ;-)
