### ISSUE TITLE
Draggable and Droppable plugins on GitHub are different versions??

### ISSUE THREAD

**Issue by benjamintillman** [ArcBees/gwtquery-droppable-plugin#2]
Hello,

The draggable and droppable plugins available on GitHub don't seem to be the same version - for example, DragAndDropManagerImpl.java in the droppable plugin overrides several functions that have different signatures in the DragAndDropManager.java class from the draggable plugin.

Some examples:

public void drag(DragContext ctx, GqEvent e) { /* from draggable plugin */ }

@Override
public void drag(Element draggable, GqEvent e) { /* from droppable plugin */ }

I checked out the source code from Google Code to see what was going on, and it seems the '(Element draggable, GqEvent e)' versions have been added later (going by the commit dates on Google Code), which suggests the droppable plugin on GitHub is more recent than the draggable plugin also on GitHub.

Any help getting these two plugins in line would be great.

Cheers,
Ben.

**Comment by jclariviere** [comment]
Fixed by #7
